font_family                 JetBrainsMono Nerd Font
font_size                   13
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
remember_window_size        no
initial_window_width        950
initial_window_height       500
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
window_padding_width        10
hide_window_decorations     yes
confirm_os_window_close     0
selection_foreground        none
selection_background        none

cursor_trail 1 
cursor #e0e2e8
cursor_text_color #c2c7cf
cursor_shape beam
mouse_hide_wait -1

foreground            #e0e2e8
background            #101418
selection_foreground  #000000
selection_background  #8ab4f8
url_color             #42a5f5

